unitDef = {
  unitname                      = [[storagedrone]],
  name                          = [[Failbox]],
  description                   = [[Useless pile of Fuck]],
  acceleration           = 0.25,
  activateWhenBuilt      = true,
  brakeRate              = 0.4,
  buildCostEnergy        = 100,
  buildCostMetal         = 100,
  builder                = false,
  buildTime              = 100,
  canMove                = true,
  canstop                = [[1]],
  category                      = [[SINK]],
  buildPic                      = [[ARMMSTOR.png]],
  collisionVolumeOffsets        = [[0 0 0]],
  collisionVolumeScales         = [[60 60 60]],
  collisionVolumeTest           = 1,
  collisionVolumeType           = [[ellipsoid]], 
  corpse                        = [[DEAD]],
  explodeAs                     = [[SMALL_BUILDINGEX]],
  footprintX                    = 3,
  footprintZ                    = 3,
  iconType                      = [[mex]],
  idleAutoHeal                  = 5,
  idleTime                      = 1800,  
mass                   = 100,
  maxDamage                     = 1000,
  movementClass          = [[AKBOT2]],
  maxSlope               = 36,
  maxVelocity            = 3,
  maxWaterDepth          = 15,
  minCloakDistance              = 80,
  noAutoFire                    = false,
  objectName                    = [[pylon.s3o]],
  seismicSignature              = 4,
  selfDestructAs                = [[ATOMIC_BLAST]],
  side                          = [[ARM]],
  sightDistance                 = 400,
  smoothAnim                    = true,
  TEDClass                      = [[METAL]],
  turnRate                      = 1,
  workerTime                    = 0,
  script			= [[armestor.cob]],
  sounds			= {select = 'reply/building_select2',},
  kamikaze               = true, 
  kamikazeDistance       = 190,

  kamikazeUseLOS         = true,
  selfDestructCountdown  = 0,
  initCloaked            = false,
  decloakOnFire          = false,
  cloakCost              = 0,

  customParams                  = {
	helptext       = [[Fail boxes contain all the fail you have. When an enemy comes by, they get failed to death. Get it?]],
	modelradius    = [[30]],
  },
  
  featureDefs                   = {

    DEAD  = {
      description      = [[Wreckage - Metal Storage]],
      blocking         = true,
      category         = [[corpses]],
      damage           = 700,
      energy           = 0,
      featureDead      = [[DEAD2]],
      featurereclamate = [[SMUDGE01]],
      footprintX       = 4,
      footprintZ       = 4,
      height           = [[40]],
      hitdensity       = [[100]],
      metal            = 40,
      object           = [[debris4x4c.s3o]],
      reclaimable      = true,
      reclaimTime      = 40,
      seqnamereclamate = [[TREE1RECLAMATE]],
      world            = [[All Worlds]],
    },


    DEAD2 = {
      description      = [[Debris - Metal Storage]],
      blocking         = false,
      category         = [[heaps]],
      damage           = 700,
      energy           = 0,
      featureDead      = [[HEAP]],
      featurereclamate = [[SMUDGE01]],
      footprintX       = 4,
      footprintZ       = 4,
      height           = [[4]],
      hitdensity       = [[100]],
      metal            = 40,
      object           = [[debris4x4c.s3o]],
      reclaimable      = true,
      reclaimTime      = 40,
      seqnamereclamate = [[TREE1RECLAMATE]],
      world            = [[All Worlds]],
    },


    HEAP  = {
      description      = [[Debris - Metal Storage]],
      blocking         = false,
      category         = [[heaps]],
      damage           = 700,
      energy           = 0,
      featurereclamate = [[SMUDGE01]],
      footprintX       = 4,
      footprintZ       = 4,
      height           = [[4]],
      hitdensity       = [[100]],
      metal            = 20,
      object           = [[debris4x4c.s3o]],
      reclaimable      = true,
      reclaimTime      = 20,
      seqnamereclamate = [[TREE1RECLAMATE]],
      world            = [[All Worlds]],
    },

  },

}

unitDef.weaponDefs = weaponDefs
return lowerkeys({ storagedrone = unitDef })
